apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader
spec:
  selector:
    matchLabels:
      app: leader
  replicas: 1
  template:
    metadata:
      labels:
        app: leader
    spec:
      containers:
        - name: leader
          image: staleread/hmp-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: hmp-config
            - secretRef:
                name: hmp-secret

---

apiVersion: v1
kind: Service
metadata:
  name: leader
spec:
  selector:
    app: leader
  ports:
    - port: 80
      targetPort: 8000
